// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7naeV79NXVqKpjYS6z4VhJfIKxMbTBWI',
    appId: '1:533383877066:web:bfd8baa44aa341cf0fff33',
    messagingSenderId: '533383877066',
    projectId: 'vitor-firebase-teste',
    authDomain: 'vitor-firebase-teste.firebaseapp.com',
    storageBucket: 'vitor-firebase-teste.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPwsmLnPlXOhIFUyQKugSu5fLNmJC-n7A',
    appId: '1:533383877066:android:24650540da9ec86b0fff33',
    messagingSenderId: '533383877066',
    projectId: 'vitor-firebase-teste',
    storageBucket: 'vitor-firebase-teste.appspot.com',
  );
}
